on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  analyze:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main

  dusk_analyzer:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  test_nightly:
    name: Nightly test all features
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --all-features

  test_nightly_no_std:
    name: Nightly tests no_std
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --no-default-features